<?php
/**
 * LineItemProperties
 *
 * PHP version 5
 *
 * @category Class
 * @package  Johncarlson21\EbaySdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Fulfillment API
 *
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: v1.20.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.47-SNAPSHOT
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Johncarlson21\EbaySdk\Johncarlson21\EbaySdk\Model;

use \ArrayAccess;
use \Johncarlson21\EbaySdk\ObjectSerializer;

/**
 * LineItemProperties Class Doc Comment
 *
 * @category Class
 * @description This type contains information about the eBay programs under which a line item was listed and sold.
 * @package  Johncarlson21\EbaySdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class LineItemProperties implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'LineItemProperties';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'buyerProtection' => 'bool',
        'fromBestOffer' => 'bool',
        'soldViaAdCampaign' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'buyerProtection' => null,
        'fromBestOffer' => null,
        'soldViaAdCampaign' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'buyerProtection' => 'buyerProtection',
        'fromBestOffer' => 'fromBestOffer',
        'soldViaAdCampaign' => 'soldViaAdCampaign'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'buyerProtection' => 'setBuyerProtection',
        'fromBestOffer' => 'setFromBestOffer',
        'soldViaAdCampaign' => 'setSoldViaAdCampaign'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'buyerProtection' => 'getBuyerProtection',
        'fromBestOffer' => 'getFromBestOffer',
        'soldViaAdCampaign' => 'getSoldViaAdCampaign'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['buyerProtection'] = isset($data['buyerProtection']) ? $data['buyerProtection'] : null;
        $this->container['fromBestOffer'] = isset($data['fromBestOffer']) ? $data['fromBestOffer'] : null;
        $this->container['soldViaAdCampaign'] = isset($data['soldViaAdCampaign']) ? $data['soldViaAdCampaign'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets buyerProtection
     *
     * @return bool
     */
    public function getBuyerProtection()
    {
        return $this->container['buyerProtection'];
    }

    /**
     * Sets buyerProtection
     *
     * @param bool $buyerProtection A value of <code>true</code> indicates that the line item is covered by eBay's Buyer Protection program.
     *
     * @return $this
     */
    public function setBuyerProtection($buyerProtection)
    {
        $this->container['buyerProtection'] = $buyerProtection;

        return $this;
    }

    /**
     * Gets fromBestOffer
     *
     * @return bool
     */
    public function getFromBestOffer()
    {
        return $this->container['fromBestOffer'];
    }

    /**
     * Sets fromBestOffer
     *
     * @param bool $fromBestOffer This field is only returned if <code>true</code> and indicates that the purchase occurred by the buyer and seller mutually agreeing on a Best Offer amount. The Best Offer feature can be set up for any listing type, but if this feature is set up for an auction listing, it will no longer be available once a bid has been placed on the listing.
     *
     * @return $this
     */
    public function setFromBestOffer($fromBestOffer)
    {
        $this->container['fromBestOffer'] = $fromBestOffer;

        return $this;
    }

    /**
     * Gets soldViaAdCampaign
     *
     * @return bool
     */
    public function getSoldViaAdCampaign()
    {
        return $this->container['soldViaAdCampaign'];
    }

    /**
     * Sets soldViaAdCampaign
     *
     * @param bool $soldViaAdCampaign This field is only returned if <code>true</code> and indicates that the line item was sold as a result of a seller's ad campaign.
     *
     * @return $this
     */
    public function setSoldViaAdCampaign($soldViaAdCampaign)
    {
        $this->container['soldViaAdCampaign'] = $soldViaAdCampaign;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
