<?php
/**
 * PricingSummary
 *
 * PHP version 5
 *
 * @category Class
 * @package  Johncarlson21\EbaySdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Fulfillment API
 *
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: v1.20.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.47-SNAPSHOT
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Johncarlson21\EbaySdk\Johncarlson21\EbaySdk\Model;

use \ArrayAccess;
use \Johncarlson21\EbaySdk\ObjectSerializer;

/**
 * PricingSummary Class Doc Comment
 *
 * @category Class
 * @description This type contains a summary of cumulative costs and charges for all line items of an order, including item price, price adjustments, sales taxes, delivery costs, and order discounts.
 * @package  Johncarlson21\EbaySdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PricingSummary implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'PricingSummary';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'adjustment' => '\Johncarlson21\EbaySdk\Johncarlson21\EbaySdk\Model\Amount',
        'deliveryCost' => '\Johncarlson21\EbaySdk\Johncarlson21\EbaySdk\Model\Amount',
        'deliveryDiscount' => '\Johncarlson21\EbaySdk\Johncarlson21\EbaySdk\Model\Amount',
        'fee' => '\Johncarlson21\EbaySdk\Johncarlson21\EbaySdk\Model\Amount',
        'priceDiscount' => '\Johncarlson21\EbaySdk\Johncarlson21\EbaySdk\Model\Amount',
        'priceSubtotal' => '\Johncarlson21\EbaySdk\Johncarlson21\EbaySdk\Model\Amount',
        'tax' => '\Johncarlson21\EbaySdk\Johncarlson21\EbaySdk\Model\Amount',
        'total' => '\Johncarlson21\EbaySdk\Johncarlson21\EbaySdk\Model\Amount'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'adjustment' => null,
        'deliveryCost' => null,
        'deliveryDiscount' => null,
        'fee' => null,
        'priceDiscount' => null,
        'priceSubtotal' => null,
        'tax' => null,
        'total' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'adjustment' => 'adjustment',
        'deliveryCost' => 'deliveryCost',
        'deliveryDiscount' => 'deliveryDiscount',
        'fee' => 'fee',
        'priceDiscount' => 'priceDiscount',
        'priceSubtotal' => 'priceSubtotal',
        'tax' => 'tax',
        'total' => 'total'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'adjustment' => 'setAdjustment',
        'deliveryCost' => 'setDeliveryCost',
        'deliveryDiscount' => 'setDeliveryDiscount',
        'fee' => 'setFee',
        'priceDiscount' => 'setPriceDiscount',
        'priceSubtotal' => 'setPriceSubtotal',
        'tax' => 'setTax',
        'total' => 'setTotal'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'adjustment' => 'getAdjustment',
        'deliveryCost' => 'getDeliveryCost',
        'deliveryDiscount' => 'getDeliveryDiscount',
        'fee' => 'getFee',
        'priceDiscount' => 'getPriceDiscount',
        'priceSubtotal' => 'getPriceSubtotal',
        'tax' => 'getTax',
        'total' => 'getTotal'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['adjustment'] = isset($data['adjustment']) ? $data['adjustment'] : null;
        $this->container['deliveryCost'] = isset($data['deliveryCost']) ? $data['deliveryCost'] : null;
        $this->container['deliveryDiscount'] = isset($data['deliveryDiscount']) ? $data['deliveryDiscount'] : null;
        $this->container['fee'] = isset($data['fee']) ? $data['fee'] : null;
        $this->container['priceDiscount'] = isset($data['priceDiscount']) ? $data['priceDiscount'] : null;
        $this->container['priceSubtotal'] = isset($data['priceSubtotal']) ? $data['priceSubtotal'] : null;
        $this->container['tax'] = isset($data['tax']) ? $data['tax'] : null;
        $this->container['total'] = isset($data['total']) ? $data['total'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets adjustment
     *
     * @return \Johncarlson21\EbaySdk\Johncarlson21\EbaySdk\Model\Amount
     */
    public function getAdjustment()
    {
        return $this->container['adjustment'];
    }

    /**
     * Sets adjustment
     *
     * @param \Johncarlson21\EbaySdk\Johncarlson21\EbaySdk\Model\Amount $adjustment adjustment
     *
     * @return $this
     */
    public function setAdjustment($adjustment)
    {
        $this->container['adjustment'] = $adjustment;

        return $this;
    }

    /**
     * Gets deliveryCost
     *
     * @return \Johncarlson21\EbaySdk\Johncarlson21\EbaySdk\Model\Amount
     */
    public function getDeliveryCost()
    {
        return $this->container['deliveryCost'];
    }

    /**
     * Sets deliveryCost
     *
     * @param \Johncarlson21\EbaySdk\Johncarlson21\EbaySdk\Model\Amount $deliveryCost deliveryCost
     *
     * @return $this
     */
    public function setDeliveryCost($deliveryCost)
    {
        $this->container['deliveryCost'] = $deliveryCost;

        return $this;
    }

    /**
     * Gets deliveryDiscount
     *
     * @return \Johncarlson21\EbaySdk\Johncarlson21\EbaySdk\Model\Amount
     */
    public function getDeliveryDiscount()
    {
        return $this->container['deliveryDiscount'];
    }

    /**
     * Sets deliveryDiscount
     *
     * @param \Johncarlson21\EbaySdk\Johncarlson21\EbaySdk\Model\Amount $deliveryDiscount deliveryDiscount
     *
     * @return $this
     */
    public function setDeliveryDiscount($deliveryDiscount)
    {
        $this->container['deliveryDiscount'] = $deliveryDiscount;

        return $this;
    }

    /**
     * Gets fee
     *
     * @return \Johncarlson21\EbaySdk\Johncarlson21\EbaySdk\Model\Amount
     */
    public function getFee()
    {
        return $this->container['fee'];
    }

    /**
     * Sets fee
     *
     * @param \Johncarlson21\EbaySdk\Johncarlson21\EbaySdk\Model\Amount $fee fee
     *
     * @return $this
     */
    public function setFee($fee)
    {
        $this->container['fee'] = $fee;

        return $this;
    }

    /**
     * Gets priceDiscount
     *
     * @return \Johncarlson21\EbaySdk\Johncarlson21\EbaySdk\Model\Amount
     */
    public function getPriceDiscount()
    {
        return $this->container['priceDiscount'];
    }

    /**
     * Sets priceDiscount
     *
     * @param \Johncarlson21\EbaySdk\Johncarlson21\EbaySdk\Model\Amount $priceDiscount priceDiscount
     *
     * @return $this
     */
    public function setPriceDiscount($priceDiscount)
    {
        $this->container['priceDiscount'] = $priceDiscount;

        return $this;
    }

    /**
     * Gets priceSubtotal
     *
     * @return \Johncarlson21\EbaySdk\Johncarlson21\EbaySdk\Model\Amount
     */
    public function getPriceSubtotal()
    {
        return $this->container['priceSubtotal'];
    }

    /**
     * Sets priceSubtotal
     *
     * @param \Johncarlson21\EbaySdk\Johncarlson21\EbaySdk\Model\Amount $priceSubtotal priceSubtotal
     *
     * @return $this
     */
    public function setPriceSubtotal($priceSubtotal)
    {
        $this->container['priceSubtotal'] = $priceSubtotal;

        return $this;
    }

    /**
     * Gets tax
     *
     * @return \Johncarlson21\EbaySdk\Johncarlson21\EbaySdk\Model\Amount
     */
    public function getTax()
    {
        return $this->container['tax'];
    }

    /**
     * Sets tax
     *
     * @param \Johncarlson21\EbaySdk\Johncarlson21\EbaySdk\Model\Amount $tax tax
     *
     * @return $this
     */
    public function setTax($tax)
    {
        $this->container['tax'] = $tax;

        return $this;
    }

    /**
     * Gets total
     *
     * @return \Johncarlson21\EbaySdk\Johncarlson21\EbaySdk\Model\Amount
     */
    public function getTotal()
    {
        return $this->container['total'];
    }

    /**
     * Sets total
     *
     * @param \Johncarlson21\EbaySdk\Johncarlson21\EbaySdk\Model\Amount $total total
     *
     * @return $this
     */
    public function setTotal($total)
    {
        $this->container['total'] = $total;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
