<?php
/**
 * Program
 *
 * PHP version 5
 *
 * @category Class
 * @package  Johncarlson21\EbaySdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Fulfillment API
 *
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: v1.20.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.47-SNAPSHOT
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Johncarlson21\EbaySdk\Model;

use \ArrayAccess;
use \Johncarlson21\EbaySdk\ObjectSerializer;

/**
 * Program Class Doc Comment
 *
 * @category Class
 * @description This type is returned for order line items eligible for the Authenticity Guarantee service and/or for order line items fulfilled by the eBay Fulfillment program or eBay shipping.
 * @package  Johncarlson21\EbaySdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Program implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'Program';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'authenticityVerification' => '\Johncarlson21\EbaySdk\Model\PostSaleAuthenticationProgram',
        'ebayShipping' => '\Johncarlson21\EbaySdk\Model\EbayShipping',
        'ebayVault' => '\Johncarlson21\EbaySdk\Model\EbayVaultProgram',
        'ebayInternationalShipping' => '\Johncarlson21\EbaySdk\Model\EbayInternationalShipping',
        'fulfillmentProgram' => '\Johncarlson21\EbaySdk\Model\EbayFulfillmentProgram'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'authenticityVerification' => null,
        'ebayShipping' => null,
        'ebayVault' => null,
        'ebayInternationalShipping' => null,
        'fulfillmentProgram' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'authenticityVerification' => 'authenticityVerification',
        'ebayShipping' => 'ebayShipping',
        'ebayVault' => 'ebayVault',
        'ebayInternationalShipping' => 'ebayInternationalShipping',
        'fulfillmentProgram' => 'fulfillmentProgram'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'authenticityVerification' => 'setAuthenticityVerification',
        'ebayShipping' => 'setEbayShipping',
        'ebayVault' => 'setEbayVault',
        'ebayInternationalShipping' => 'setEbayInternationalShipping',
        'fulfillmentProgram' => 'setFulfillmentProgram'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'authenticityVerification' => 'getAuthenticityVerification',
        'ebayShipping' => 'getEbayShipping',
        'ebayVault' => 'getEbayVault',
        'ebayInternationalShipping' => 'getEbayInternationalShipping',
        'fulfillmentProgram' => 'getFulfillmentProgram'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['authenticityVerification'] = isset($data['authenticityVerification']) ? $data['authenticityVerification'] : null;
        $this->container['ebayShipping'] = isset($data['ebayShipping']) ? $data['ebayShipping'] : null;
        $this->container['ebayVault'] = isset($data['ebayVault']) ? $data['ebayVault'] : null;
        $this->container['ebayInternationalShipping'] = isset($data['ebayInternationalShipping']) ? $data['ebayInternationalShipping'] : null;
        $this->container['fulfillmentProgram'] = isset($data['fulfillmentProgram']) ? $data['fulfillmentProgram'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets authenticityVerification
     *
     * @return \Johncarlson21\EbaySdk\Model\PostSaleAuthenticationProgram
     */
    public function getAuthenticityVerification()
    {
        return $this->container['authenticityVerification'];
    }

    /**
     * Sets authenticityVerification
     *
     * @param \Johncarlson21\EbaySdk\Model\PostSaleAuthenticationProgram $authenticityVerification authenticityVerification
     *
     * @return $this
     */
    public function setAuthenticityVerification($authenticityVerification)
    {
        $this->container['authenticityVerification'] = $authenticityVerification;

        return $this;
    }

    /**
     * Gets ebayShipping
     *
     * @return \Johncarlson21\EbaySdk\Model\EbayShipping
     */
    public function getEbayShipping()
    {
        return $this->container['ebayShipping'];
    }

    /**
     * Sets ebayShipping
     *
     * @param \Johncarlson21\EbaySdk\Model\EbayShipping $ebayShipping ebayShipping
     *
     * @return $this
     */
    public function setEbayShipping($ebayShipping)
    {
        $this->container['ebayShipping'] = $ebayShipping;

        return $this;
    }

    /**
     * Gets ebayVault
     *
     * @return \Johncarlson21\EbaySdk\Model\EbayVaultProgram
     */
    public function getEbayVault()
    {
        return $this->container['ebayVault'];
    }

    /**
     * Sets ebayVault
     *
     * @param \Johncarlson21\EbaySdk\Model\EbayVaultProgram $ebayVault ebayVault
     *
     * @return $this
     */
    public function setEbayVault($ebayVault)
    {
        $this->container['ebayVault'] = $ebayVault;

        return $this;
    }

    /**
     * Gets ebayInternationalShipping
     *
     * @return \Johncarlson21\EbaySdk\Model\EbayInternationalShipping
     */
    public function getEbayInternationalShipping()
    {
        return $this->container['ebayInternationalShipping'];
    }

    /**
     * Sets ebayInternationalShipping
     *
     * @param \Johncarlson21\EbaySdk\Model\EbayInternationalShipping $ebayInternationalShipping ebayInternationalShipping
     *
     * @return $this
     */
    public function setEbayInternationalShipping($ebayInternationalShipping)
    {
        $this->container['ebayInternationalShipping'] = $ebayInternationalShipping;

        return $this;
    }

    /**
     * Gets fulfillmentProgram
     *
     * @return \Johncarlson21\EbaySdk\Model\EbayFulfillmentProgram
     */
    public function getFulfillmentProgram()
    {
        return $this->container['fulfillmentProgram'];
    }

    /**
     * Sets fulfillmentProgram
     *
     * @param \Johncarlson21\EbaySdk\Model\EbayFulfillmentProgram $fulfillmentProgram fulfillmentProgram
     *
     * @return $this
     */
    public function setFulfillmentProgram($fulfillmentProgram)
    {
        $this->container['fulfillmentProgram'] = $fulfillmentProgram;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
