<?php
/**
 * LinkedOrderLineItemTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Johncarlson21\EbaySdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Fulfillment API
 *
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: v1.20.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.47-SNAPSHOT
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Johncarlson21\EbaySdk;

use PHPUnit\Framework\TestCase;

/**
 * LinkedOrderLineItemTest Class Doc Comment
 *
 * @category    Class
 * @description This type contains data on a line item that is related to, but not a part of the order.
 * @package     Johncarlson21\EbaySdk
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LinkedOrderLineItemTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "LinkedOrderLineItem"
     */
    public function testLinkedOrderLineItem()
    {
    }

    /**
     * Test attribute "lineItemAspects"
     */
    public function testPropertyLineItemAspects()
    {
    }

    /**
     * Test attribute "lineItemId"
     */
    public function testPropertyLineItemId()
    {
    }

    /**
     * Test attribute "maxEstimatedDeliveryDate"
     */
    public function testPropertyMaxEstimatedDeliveryDate()
    {
    }

    /**
     * Test attribute "minEstimatedDeliveryDate"
     */
    public function testPropertyMinEstimatedDeliveryDate()
    {
    }

    /**
     * Test attribute "orderId"
     */
    public function testPropertyOrderId()
    {
    }

    /**
     * Test attribute "sellerId"
     */
    public function testPropertySellerId()
    {
    }

    /**
     * Test attribute "shipments"
     */
    public function testPropertyShipments()
    {
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
    }
}
