<?php
/**
 * PaymentHoldTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Johncarlson21\EbaySdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Fulfillment API
 *
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: v1.20.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.47-SNAPSHOT
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Johncarlson21\EbaySdk;

use PHPUnit\Framework\TestCase;

/**
 * PaymentHoldTest Class Doc Comment
 *
 * @category    Class
 * @description This type contains information about a hold placed on a payment to a seller for an order, including the reason why the buyer&#x27;s payment for the order is being held, the expected release date of the funds into the seller&#x27;s account, the current state of the hold, and the actual release date if the payment has been released, and possible actions the seller can take to expedite the payout of funds into their account.
 * @package     Johncarlson21\EbaySdk
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PaymentHoldTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PaymentHold"
     */
    public function testPaymentHold()
    {
    }

    /**
     * Test attribute "expectedReleaseDate"
     */
    public function testPropertyExpectedReleaseDate()
    {
    }

    /**
     * Test attribute "holdAmount"
     */
    public function testPropertyHoldAmount()
    {
    }

    /**
     * Test attribute "holdReason"
     */
    public function testPropertyHoldReason()
    {
    }

    /**
     * Test attribute "holdState"
     */
    public function testPropertyHoldState()
    {
    }

    /**
     * Test attribute "releaseDate"
     */
    public function testPropertyReleaseDate()
    {
    }

    /**
     * Test attribute "sellerActionsToRelease"
     */
    public function testPropertySellerActionsToRelease()
    {
    }
}
