<?php
/**
 * ReturnAddressTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Johncarlson21\EbaySdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Fulfillment API
 *
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: v1.20.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.47-SNAPSHOT
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Johncarlson21\EbaySdk;

use PHPUnit\Framework\TestCase;

/**
 * ReturnAddressTest Class Doc Comment
 *
 * @category    Class
 * @description This type is used by the payment dispute methods, and is relevant if the buyer will be returning the item to the seller.
 * @package     Johncarlson21\EbaySdk
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ReturnAddressTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ReturnAddress"
     */
    public function testReturnAddress()
    {
    }

    /**
     * Test attribute "addressLine1"
     */
    public function testPropertyAddressLine1()
    {
    }

    /**
     * Test attribute "addressLine2"
     */
    public function testPropertyAddressLine2()
    {
    }

    /**
     * Test attribute "city"
     */
    public function testPropertyCity()
    {
    }

    /**
     * Test attribute "country"
     */
    public function testPropertyCountry()
    {
    }

    /**
     * Test attribute "county"
     */
    public function testPropertyCounty()
    {
    }

    /**
     * Test attribute "fullName"
     */
    public function testPropertyFullName()
    {
    }

    /**
     * Test attribute "postalCode"
     */
    public function testPropertyPostalCode()
    {
    }

    /**
     * Test attribute "primaryPhone"
     */
    public function testPropertyPrimaryPhone()
    {
    }

    /**
     * Test attribute "stateOrProvince"
     */
    public function testPropertyStateOrProvince()
    {
    }
}
