<?php
/**
 * ShippingFulfillmentDetailsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Johncarlson21\EbaySdk
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Fulfillment API
 *
 * Use the Fulfillment API to complete the process of packaging, addressing, handling, and shipping each order on behalf of the seller, in accordance with the payment method and timing specified at checkout.
 *
 * OpenAPI spec version: v1.20.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.47-SNAPSHOT
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Johncarlson21\EbaySdk;

use PHPUnit\Framework\TestCase;

/**
 * ShippingFulfillmentDetailsTest Class Doc Comment
 *
 * @category    Class
 * @description This type contains the details for creating a fulfillment for an order.
 * @package     Johncarlson21\EbaySdk
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ShippingFulfillmentDetailsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ShippingFulfillmentDetails"
     */
    public function testShippingFulfillmentDetails()
    {
    }

    /**
     * Test attribute "lineItems"
     */
    public function testPropertyLineItems()
    {
    }

    /**
     * Test attribute "shippedDate"
     */
    public function testPropertyShippedDate()
    {
    }

    /**
     * Test attribute "shippingCarrierCode"
     */
    public function testPropertyShippingCarrierCode()
    {
    }

    /**
     * Test attribute "trackingNumber"
     */
    public function testPropertyTrackingNumber()
    {
    }
}
